swagger:
  show: true
server:
  port: 8081
logging:
  config: classpath:log/logback.xml
spring:
  application:
    name: opay-invite
  datasource:
    url: jdbc:mysql://localhost:3306/opay_invite?useSSL=false&useAffectedRows=true&allowMultiQueries=true
    username: root
    password: 04cdf9719ba61283
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 8
      min-idle: 1
      max-active: 20
      max-wait: 60000
      time-between-eviction-runsMillis: 60000
      min-evictable-idle-timeMillis: 300000
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      use-global-data-source-stat: true
      filter:
        stat:
          db-type: mysql
          log-slow-sql: true
          slow-sql-millis: 2000
        wall:
          enabled: false
          db-type: mysql
          config:
            delete-allow: false
            drop-table-allow: false
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 2000
    lettuce:
      pool:
        max-active: 8
        max-wait: 1
        max-idle: 8
        min-idle: 0
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+1
  quartz:
    properties:
      scheduler:
        instanceName: opay.invite
        instanceId: AUTO
      jobStore:
        misfireThreshold: 60000
        class: org.quartz.impl.jdbcjobstore.JobStoreTX
        driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
        dataSource: qrtz
        tablePrefix: QRTZ_
        isClustered: true
        clusterCheckinInterval: 2000
      dataSource:
        qrtz:
          driver: "com.mysql.jdbc.Driver"
          validationQuery: "select 1"
          URL: "jdbc:mysql://localhost:3306/opay_invite?useUnicode=true&characterEncoding=utf-8"
          user: "root"
          password: "04cdf9719ba61283"
config:
  opay:
    domain: http://api.test.opaydev.com:8081
    merchantId: 256619120522011
    aesKey: gepy7T6jTldRMq7A
    iv: qazwert12345!@#$

activity:
  reward:
    registerReward: 1
    masterReward: 1
    rechargeReward: 2
    agentOpen: 1
    startTime: 2019-11-23 00:00:00
    endTime: 2020-02-18 21:00:00
    effectiveDay: 7
    turntableStart: 2019-12-06 00:00:01
    turntableEnd: 2020-02-26 00:00:01
    rewardList[0]:
      orderId: 1
      min: 1
      max: 5
      walletReward: 2
      totalReward: 15
    rewardList[1]:
      orderId: 2
      min: 6
      max: 7
      walletReward: 3
      totalReward: 20
    rewardList[2]:
      orderId: 3
      min: 8
      max: 20
      walletReward: 4
      totalReward: 50
    rewardList[3]:
      orderId: 4
      min: 21
      max: 30
      walletReward: 5
      totalReward: 60
    rewardList[4]:
      orderId: 4
      min: 31
      max: 50
      walletReward: 6
      totalReward: 140
    rewardList[5]:
      orderId: 4
      min: 51
      max: 100
      walletReward: 7
      totalReward: 400
    rewardList[6]:
      orderId: 4
      min: 101
      max: 200
      walletReward: 8
      totalReward: 900
    rewardList[7]:
      orderId: 4
      min: 201
      max: 500
      walletReward: 9
      totalReward: 3000
    rewardList[8]:
      orderId: 4
      min: 501
      max: 2000
      walletReward: 10
      totalReward: 16500
    royList[0]:
      action: 3
      masterReward: 1
      pupilReward: 1
#    royList[1]:
#      action: 4
#      masterReward: 0.3
#      pupilReward: 0.3
#    royList[2]:
#      action: 5
#      masterReward: 1
#      pupilReward: 1
tixian:
  limit:
    open: 1
    perDayAmount: 5
    perAmount: 2
    list[0]:
      min: 0
      max: 24
      minAmount: 10

invite:
  code: opay9102c7uw27er4$!=
  productKey: opay9102codec7uw27er4$!=

transfer:
  opay:
    domain: http://api.test.opaydev.com:8081
    merchantId: 256619120522011
    aesKey: gepy7T6jTldRMq7A
    iv: qazwert12345!@#$
    url: /api/m/createOrder
    reference: IVE
    userUrl: /api/users/queryUserInfoByPhone
    userRecordUrl: /api/im/queryUserRecordByPhone
    transferNotify: http://t-api.iminvite.pos.operapay.com/invite/api/transferNotify

opay:
  settings:
    jobs:
      fix-user-trade:
        expression: "19 47 10 * * ?"
        jobClass: "com.opay.invite.job.UserTradeJob"
      fix-user-reward:
        expression: "05 56 12 * * ?"
        jobClass: "com.opay.invite.job.RewardJob"
      first-luck-draw:
        expression: "0 50 2 * * ?"
        jobClass: "com.opay.invite.job.InitPrizePoolJob"
      second-luck-draw:
        expression: "0 50 5 * * ?"
        jobClass: "com.opay.invite.job.InitPrizePoolJob"
#  luckDraw:
#    callBack: http://t-api.iminvite.pos.operapay.com/invite/callback/bonus
#    merchantId: 9552000218
#    aesKey: HKFbWOqM5Kd3a7N9
#    iv: qazwert12345!@#$
#    publickey: OPAYPUB15767581742580.8873746461850968
#    privatekey: OPAYPRV15767581742580.6213051058973535
  luckDraw:
    callBack: http://t-api.iminvite.pos.operapay.com/invite/callback/bonus
    merchantId: 256619120522011
    aesKey: gepy7T6jTldRMq7A
    iv: qazwert12345!@#$
    publickey: OPAYPUB15755298483140.9696556588602406
    privatekey: OPAYPRV15755298483140.06665533965779369

management:
  endpoints:
    web:
      exposure:
        include:  '*'
  metrics:
    tags:
      application: ${spring.application.name}
prometheus:
  client:
    enabled: true
    basePackage: com.opay.invite
feign:
  httpclient:
    connectionTimeout: 5000
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
#prize-pool:
#  inviteLimit: 100
#  shareLimit: 3 #每天分享上线
#  grandPrizeIndex: 1000 #还剩n次时,开出大奖
#  firstGrandPrizeTimeUp: "10:50:00"
#  secondGrandPrizeTimeUp: "10:50:00"
#  secondPoolRate: 4
#  count: 100000
#  firstPoolStart: 2
#  firstPoolEnd: 3
#  secondPoolStart: 4
#  secondPoolEnd: 5
#  firstPool:
#    - {prize: 10,prob: 0.00015}
#    - {prize: 5,prob: 0.0002}
#    - {prize: 2,prob: 0.001}
#    - {prize: 1,prob: 0.24865}
#    - {prize: 0,prob: 0.75}
#  secondPool:
#    - {prize: phone,prob: 0.00001}
#    - {prize: 100,prob: 0.00004}
#    - {prize: 50,prob: 0.0002}
#    - {prize: 10,prob: 0.00035}
#    - {prize: 5,prob: 0.0009}
#    - {prize: 2,prob: 0.0285}
#    - {prize: 1,prob: 0.27}
#    - {prize: 0,prob: 0.7}
prize-pool:
  inviteLimit: 100
  shareLimit: 3 #每天分享上线
  grandPrizeIndex: 1238 #还剩n次时,开出大奖
  firstGrandPrizeTimeUp: "4:45:00"
  secondGrandPrizeTimeUp: "14:50:00"
  secondPoolRate: 4
  count: 100000
  firstPoolStart: 3
  firstPoolEnd: 5
  secondPoolStart: 6
  secondPoolEnd: 15
  activityStart: 2019-12-06 00:00:01
  activityEnd: 2029-12-21 10:00:00
  firstPool:
    - {id: 4,prize: 10,prob: 0.00015}
    - {id: 5,prize: 5,prob: 0.0002}
    - {id: 6,prize: 2,prob: 0.001}
    - {id: 7,prize: 1,prob: 0.24865}
    - {id: 8,prize: 0,prob: 0.75}
  secondPool:
    - {id: 1,prize: phone,prob: 0.00001}
    - {id: 2,prize: 100,prob: 0.00004}
    - {id: 3,prize: 50,prob: 0.0002}
    - {id: 4,prize: 10,prob: 0.00035}
    - {id: 5,prize: 5,prob: 0.0009}
    - {id: 6,prize: 2,prob: 0.0285}
    - {id: 7,prize: 1,prob: 0.27}
    - {id: 8,prize: 0,prob: 0.7}
