server:
  port: 8081
logging:
  config: classpath:log/logback.xml
spring:
  application:
    name: opay-invite
  datasource:
    url: jdbc:mysql://opay-im.c7vkdm90b2v9.eu-west-1.rds.amazonaws.com:3306/opay_invite?useSSL=false&useAffectedRows=true&allowMultiQueries=true
    username: root
    password: ff3NKWQpY5hEq7xzOLuX
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 8
      min-idle: 1
      max-active: 20
      max-wait: 60000
      time-between-eviction-runsMillis: 60000
      min-evictable-idle-timeMillis: 300000
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      use-global-data-source-stat: true
      filter:
        stat:
          db-type: mysql
          log-slow-sql: true
          slow-sql-millis: 2000
        wall:
          enabled: false
          db-type: mysql
          config:
            delete-allow: false
            drop-table-allow: false
  redis:
    host: opayim.csr0wl.ng.0001.euw1.cache.amazonaws.com
    port: 6379
    timeout: 2000
    lettuce:
      pool:
        max-active: 32
        max-wait: 1000
        max-idle: 16
        min-idle: 8
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+1
  quartz:
    properties:
      scheduler:
        instanceName: opay.invite
        instanceId: AUTO
      jobStore:
        misfireThreshold: 60000
        class: org.quartz.impl.jdbcjobstore.JobStoreTX
        driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
        dataSource: qrtz
        tablePrefix: QRTZ_
        isClustered: true
        clusterCheckinInterval: 2000
      dataSource:
        qrtz:
          driver: "com.mysql.jdbc.Driver"
          validationQuery: "select 1"
          URL: "jdbc:mysql://opay-im.c7vkdm90b2v9.eu-west-1.rds.amazonaws.com:3306/opay_invite?useUnicode=true&characterEncoding=utf-8"
          user: "root"
          password: "ff3NKWQpY5hEq7xzOLuX"
config:
  opay:
    domain: http://internal-campaignapiinternal-1831570749.eu-west-1.elb.amazonaws.com
    merchantId: 256619120756000
    aesKey: f0utFRLpio5ltjH7
    iv: qazwert12345!@#$

activity:
  reward:
    registerReward: 10
    masterReward: 10
    rechargeReward: 100
    agentOpen: 0
    startTime: 2019-12-09 00:00:01
    endTime: 2020-12-09 00:00:01
    effectiveDay: 7
    turntableStart: 2019-12-06 00:00:01
    turntableEnd: 2020-12-22 00:00:01
    rewardList[0]:
      orderId: 1
      min: 1
      max: 5
      walletReward: 300
      totalReward: 1550
    rewardList[1]:
      orderId: 2
      min: 6
      max: 10
      walletReward: 320
      totalReward: 1650
    rewardList[2]:
      orderId: 3
      min: 11
      max: 20
      walletReward: 340
      totalReward: 3500
    rewardList[3]:
      orderId: 4
      min: 21
      max: 30
      walletReward: 360
      totalReward: 3700
    rewardList[4]:
      orderId: 4
      min: 31
      max: 50
      walletReward: 380
      totalReward: 7800
    rewardList[5]:
      orderId: 4
      min: 51
      max: 100
      walletReward: 400
      totalReward: 20500
    rewardList[6]:
      orderId: 4
      min: 101
      max: 200
      walletReward: 420
      totalReward: 43000
    rewardList[7]:
      orderId: 4
      min: 201
      max: 500
      walletReward: 440
      totalReward: 135000
    rewardList[8]:
      orderId: 4
      min: 501
      max: 2000
      walletReward: 460
      totalReward: 705000
    royList[0]:
      action: 3
      masterReward: 1
      pupilReward: 1
#    royList[1]:
#      action: 4
#      masterReward: 0.3
#      pupilReward: 0.3
#    royList[2]:
#      action: 5
#      masterReward: 1
#      pupilReward: 1
tixian:
  limit:
    open: 1
    perDayAmount: 3000
    perAmount: 1000
    list[0]:
      min: 0
      max: 24
      minAmount: 8000

invite:
  code: opay9102c7uw27er4uxg63h$!=
  productKey: opay9102codec7uw27er4$!=

transfer:
  opay:
    domain: http://internal-campaignapiinternal-1831570749.eu-west-1.elb.amazonaws.com
    merchantId: 256620010488001
    aesKey: IE9SSnT9VN26V1SA
    iv: qazwert12345!@#$
    url: /api/m/createOrder
    reference: IVE
    userUrl: /api/users/queryUserInfoByPhone
    userRecordUrl: /api/im/queryUserRecordByPhone
    transferNotify: https://api.iminvite.pos.operapay.com/invite/api/transferNotify

opay:
  settings:
    jobs:
      fix-user-trade:
        expression: "0 0 2 * * ?"
        jobClass: "com.opay.invite.job.UserTradeJob"
      fix-user-reward:
        expression: "0 0 3 * * ?"
        jobClass: "com.opay.invite.job.RewardJob"
      first-luck-draw:
        expression: "0 50 11 * * ?"
        jobClass: "com.opay.invite.job.InitPrizePoolJob"
      second-luck-draw:
        expression: "0 50 19 * * ?"
        jobClass: "com.opay.invite.job.InitPrizePoolJob"
  luckDraw:
    callBack: https://api.iminvite.pos.operapay.com/invite/callback/bonus
    merchantId: 256620010488002
    aesKey: Z7Sn0fmjdVQO8rgO
    iv: qazwert12345!@#$
    publickey: OPAYPUB15757135556050.8567797476826624
    privatekey: OPAYPRV15757135556050.12656111810706083

management:
  endpoints:
    web:
      exposure:
        include:  '*'
  metrics:
    tags:
      application: ${spring.application.name}
prometheus:
  client:
    enabled: true
    basePackage: com.opay.invite
feign:
  httpclient:
    connectionTimeout: 5000
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
prize-pool:
  inviteLimit: 100
  shareLimit: 3 #每天分享上线
  grandPrizeIndex: 1238 #还剩n次时,开出大奖
  firstGrandPrizeTimeUp: "13:45:00" #大奖开出时间
  secondGrandPrizeTimeUp: "21:50:00"
  secondPoolRate: 4
  count: 100000
  firstPoolStart: 06
  firstPoolEnd: 08
  secondPoolStart: 20
  secondPoolEnd: 22
  activityStart: 2019-12-06 00:00:01
  activityEnd: 2020-12-21 10:00:00
  firstPool:
    - {id: 4,prize: 10,prob: 0.00015}
    - {id: 5,prize: 5,prob: 0.0002}
    - {id: 6,prize: 2,prob: 0.001}
    - {id: 7,prize: 1,prob: 0.24865}
    - {id: 8,prize: 0,prob: 0.75}
  secondPool:
    - {id: 1,prize: phone,prob: 0.00001}
    - {id: 2,prize: 100,prob: 0.00004}
    - {id: 3,prize: 50,prob: 0.0002}
    - {id: 4,prize: 10,prob: 0.00035}
    - {id: 5,prize: 5,prob: 0.0009}
    - {id: 6,prize: 2,prob: 0.0285}
    - {id: 7,prize: 1,prob: 0.27}
    - {id: 8,prize: 0,prob: 0.7}
