swagger:
  show: true
server:
  port: 8082
logging:
  config: classpath:log/logback.xml
#app:
#  id: opay-im
#apollo:
#  meta: http://10.52.161.229:8080
#  cacheDir: ./config
#  bootstrap:
#    enabled: true
#    namespaces: application
spring:
  application:
    name: opay-im
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 20000
    lettuce:
      pool:
        max-active: 8
        max-wait: 1
        max-idle: 8
        min-idle: 0
  cache:
    type: redis
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+1

  shardingsphere:
    datasource:
      names: master
      master:
        driver-class-name: com.mysql.jdbc.Driver
        type: com.zaxxer.hikari.HikariDataSource
        jdbc-url: jdbc:mysql://localhost:3306/opay_im?useSSL=false
        username: root
        password: 04cdf9719ba61283
    sharding:
      tables:
        rong_cloud_message:
          actual-data-nodes: master.rong_cloud_message_${2019..2022}_${1..12}
          table-strategy:
            standard:
              sharding-column: msg_timestamp
              precise-algorithm-class-name: com.opay.im.config.MessagePreciseShardingAlgorithm
rongyun:
  appKey: k51hidwqk4icb
  appSecret: 02hEdHbsDuB
#config:
#  opay:
#    domain: http://api.test.opaydev.com:8081/
#    merchantId: 256619121424013
#    aesKey: 9BQ65T1cvbry9elc
#    iv: qazwert12345!@#$
#    publickey: OPAYPUB15762910236470.4044222958487964
#    privatekey: OPAYPRV15762910236470.8764696319929024
config:
  opay:
    domain: http://graphql.opaydev.com:8081/
    merchantId: 256619121714011
    aesKey: Gcn0yMfqNyDlbdbk
    iv: qazwert12345!@#$
    publickey: OPAYPUB15765525324220.5558548953180615
    privatekey: OPAYPRV15765525324220.32762670279579553
im:
  group:
    maxMember: 200
  luckyMoney:
    singleMax: 500
    dayMax: 8000
    expirationDays: 1
management:
  endpoints:
    web:
      exposure:
        include:  '*'
  metrics:
    tags:
      application: ${spring.application.name}
prometheus:
  client:
    enabled: true
    basePackage: com.opay.im