swagger:
  show: false
server:
  port: 8082
logging:
  config: classpath:log/logback.xml
#app:
#  id: opay-im
#apollo:
#  meta: http://10.52.105.56
#  cacheDir: ./config
#  bootstrap:
#    enabled: true
#    namespaces: application,FX.apollo,application.yml
spring:
  application:
    name: opay-im
  redis:
    host: opayim.csr0wl.ng.0001.euw1.cache.amazonaws.com #从opayim-ro.csr0wl.ng.0001.euw1.cache.amazonaws.com
    port: 6379
    timeout: 20000
    lettuce:
      pool:
        max-active: 40
        max-wait: 5
        max-idle: 40
        min-idle: 0
  cache:
    type: redis
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+1

  shardingsphere:
    datasource:
      names: master
      master:
        driver-class-name: com.mysql.jdbc.Driver
        type: com.zaxxer.hikari.HikariDataSource
        jdbc-url: jdbc:mysql://opay-im.c7vkdm90b2v9.eu-west-1.rds.amazonaws.com:3306/opay_im?useSSL=false
        username: root
        password: ff3NKWQpY5hEq7xzOLuX
    sharding:
      tables:
        rong_cloud_message:
          actual-data-nodes: master.rong_cloud_message_${2019..2022}_${1..12}
          table-strategy:
            standard:
              sharding-column: msg_timestamp
              precise-algorithm-class-name: com.opay.im.config.MessagePreciseShardingAlgorithm
rongyun:
  appKey: tdrvipkstyix5
  appSecret: lpTLXADqO4I3W
  api: http://api-sg01.ronghub.com
config:
  opay:
    domain: https://api.operapay.com #http://internal-campaignapiinternal-1831570749.eu-west-1.elb.amazonaws.com
    merchantId: 256619122168000
    aesKey: Xw8RjcXMoPnxfi9i
    iv: qazwert12345!@#$
    publickey: OPAYPUB15769333886080.45086047237636484
    privatekey: OPAYPRV15769333886080.03629076818522026
im:
  group:
    maxMember: 200
  luckyMoney:
    singleMax: 500
    dayMax: 8000
    expirationDays: 1
management:
  endpoints:
    web:
      exposure:
        include:  '*'
  metrics:
    tags:
      application: ${spring.application.name}
prometheus:
  client:
    enabled: true
    basePackage: com.opay.im
feign:
  httpclient:
    connectionTimeout: 5000
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
task:
  executeIp: 10.10.23.139
  minusHour:
    start: 25
    end: 24